# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'raporlar.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Rapor(object):
    def setupUi(self, Rapor):
        Rapor.setObjectName("Rapor")
        Rapor.setFixedSize(788, 611)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("report_file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Rapor.setWindowIcon(icon)
        Rapor.setIconSize(QtCore.QSize(50, 50))
        self.centralwidget = QtWidgets.QWidget(Rapor)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(260, 30, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 80, 771, 521))
        self.tableWidget.setMinimumSize(QtCore.QSize(771, 521))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tableWidget.setFont(font)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setRowCount(1)
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setBackground(QtGui.QColor(255, 255, 255))
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(700, 0, 93, 28))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        Rapor.setCentralWidget(self.centralwidget)

        self.retranslateUi(Rapor)
        QtCore.QMetaObject.connectSlotsByName(Rapor)

    def retranslateUi(self, Rapor):
        _translate = QtCore.QCoreApplication.translate
        Rapor.setWindowTitle(_translate("Rapor", "Raporlar"))
        self.label.setText(_translate("Rapor", "RAPORLAR"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Rapor", "İsim"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Rapor", "Giriş Tarihi"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Rapor", "Giriş Saati"))
        self.pushButton.setText(_translate("Rapor", "Geri Gel"))